### ISSUE TITLE
Proximity Detection?

### ISSUE THREAD

**Issue by gpetersen** [eouia/MMM-GroveGestures#1]
This looks great!  Just ordered a sensor to give it a go.  The data sheet for the sensor says:
> It also offers built-in proximity detection in sensing approaching or departing object from the sensor.

Though it's very light on details afterwards, except some Proximity Mode Controls and registers.  Have you tried this mode to see if it can also detect someone approaching the screen (e.g. standing a few feet away)?  Or is it really just the 5-20cm gesture distance?  

I'd like to have an option to show an uncluttered background picture until someone approaches, then light up a page of info, using gestures to change screens/modes as needed, then returning to the uncluttered background when they walk away.

**Comment by eouia** [comment]
Really just 5~20cm. It cannot be alternative to people detecting like PIR or cam motion detector.

**Comment by gpetersen** [comment]
That's too bad - Will look into options.  PIR may work, will look at options.  This sensor will still be useful though, thanks for getting a module wired up!
