### ISSUE TITLE
page change

### ISSUE THREAD

**Issue by altamashqureshi9144** [eouia/MMM-GroveGestures#17]
can anyone help me to change pages ???
whats the module for that...

and also can i increase or decrease the volume?

also how to stop alarm (MMM-AlarmClock)

**Comment by eouia** [comment]
MMM-GroveGestures only can emit some customized notifications. So your jobs (changing pages, controlling volume, stopping alarm) should be done by other modules which can be controllable by custom notifications.

**Comment by altamashqureshi9144** [comment]
okayy thanks
