### ISSUE TITLE
MMM-pageIndicator not changing

### ISSUE THREAD

**Issue by Antislag** [eouia/MMM-GroveGestures#19]
Hello,

I just installed MMM-groveGestures and it works like a charm with MMM-pages.
But if i send "PAGE_INCREMENT" or "PAGE_DECREMENT" only the pages changes not MMM-pageIndicator. Although its the same notification. Do I need to tell MMM-groveGestures to send the notification to both modules? If yes, how can i do it? 

Thanks in advance

**Comment by Antislag** [comment]
See MMM-page-indicator. There is a fix in issue section

**Comment by eouia** [comment]
Or you can try other paging modules, like MMM-Scenes or something.
