### ISSUE TITLE
Possibility to use 2 sensors

### ISSUE THREAD

**Issue by bolish** [eouia/MMM-GroveGestures#2]
Hi @eouia ,

I was wondring if the module would be able to handle 2 sensors?
Not talking about combining both (maybe an idea for later), but just giving the user the possibility to have 2 times more interactions with modules by putting one sensor on right side and the other on left side for example.

I'm currently building my mm project and I've to be honest, I would love that!!

Regards

**Comment by eouia** [comment]
Ah... I think it couldn't at this time. (I've never imagined)
First, I'm not sure 2 X I2C could be working at same time. Test is needed.
Second, For numerous commands, There is  "Sequence".  You can combine gestures more as you want.
By Example : "UP"-"UP"-"LEFT" or "LEFT"-"RIGHT"-"LEFT"-"DOWN"-...
So I thought there is no need to add additional gesture sensor.

**Comment by bolish** [comment]
Thanks for your prompt reply Sean.
I was not imaginating that it could be an issue to have 2 sensors but that's clearly out of my skill scope.
Anyway, thanks for having give it a thought and proposed me an alternative option through "Sequence".
I will try that as soon as I will move forward with my project.

Still...I think that having 2 sensors could be a real improvement (I'm thinking about my wife or kids).

Regards

**Comment by eouia** [comment]
If I have one more sensor to test, I'll try that feature.
I'll close this issue but you can leave more questions anytime.
