### ISSUE TITLE
More onIdle timers possible

### ISSUE THREAD

**Issue by Antislag** [eouia/MMM-GroveGestures#20]
Hello, 

I really like your module MMM-groveGestures!
And i wonder if can set additional onIdle timers.
For example onIdle after 5 minutes to start a slideshow and another onIdle after 30 minutes to shut down the monitor.

Thanks in advance

**Comment by eouia** [comment]
Sorry, onIdle is not a scheduler. Only one idle detection is affected. You need a kind of scheduling module additionally.

**Comment by Antislag** [comment]
Ok, thank you very much for the prompt answer. I will check how i can handle this and close the issue

**Comment by eouia** [comment]
MMM-NotificationTrigger allows to relay custom notification with delay.

**Comment by Antislag** [comment]
Thanks,  I'll give it try later
