### ISSUE TITLE
Notification for MMM-CalendarExt3

### ISSUE THREAD

**Issue by Antislag** [eouia/MMM-GroveGestures#21]
Hi, 

first of all thanks for the great module. It works like a charm with my MagicMirror!

I want to add a notification to change the monthly view ("UP": month +1;  "DOWN": month -1).
According to MMM-CalendarExt3 I need to add CX3_GLANCE_CALENDAR, payload: {instanceId, step}.

But if I adapt my config with
                                               "UP": {
                                                notificationExec: {
                                                notification: "CX3_GLANCE_CALENDAR",
                                                payload: {null,1}
                                                                  }
                                                         },

MagicMirror won´t start. 

With following config
                                              "UP": {
                                                notificationExec: {
                                                notification: "CX3_GLANCE_CALENDAR",
                                                payload: 1
                                                                  }
                                                         },

MagicMirror starts but if I swipe UP nothing happens. 
I´m a bloody beginner and don´t know how to proceed. Can you maybe give a hint how to solve the problem?

Thanks in advance!

**Comment by eouia** [comment]
I think `payload` was improper. Try this.

```js
payload: { step: 1 }
// Or...
// payload: { instanceId: null, step: 1 }
```

**Comment by Antislag** [comment]
Thank you so much! It works perfect.
