### ISSUE TITLE
Add ":" to your README 

### ISSUE THREAD

**Issue by ptrk95** [eouia/MMM-GroveGestures#3]
Just installed the module and everything is working fine, thanks! 
But you may want to add the double point ":" to your README, because it's causing a syntax error on the config.js if you just copy paste your example. :)

...
onIdle : { // See command section
      moduleExec: {
...

**Comment by eouia** [comment]
Thanks for report. I'll modify it on next update.

**Comment by eouia** [comment]
fixed.
