### ISSUE TITLE
possible to use it like a PIR?

### ISSUE THREAD

**Issue by smiley-2** [eouia/MMM-GroveGestures#6]
Hello,In first, sorry for my english.
I think to buy this sensor to use ith your module.

It's possible to use your module like a PIR sensor?
Per example, when the grove detect a gesture, the screen power on and if no gesture for a time, the screen power off?

thanks for your help.

**Comment by eouia** [comment]
Of course possible. This module has “onIdle” features, and ability for execution shell commands or module method or notification. The combination of features will work

**Comment by smiley-2** [comment]
thank you, you have some example? please?

**Comment by eouia** [comment]
```js
idleTimer : 60*30*1000, // onIdle will be activated in 30 Minutes from last gesture.
onIdle: {
  shellExec: "YOUR MONITOR POWER OFF SHELL COMMAND" // this command will be different per your environment 
},
onDetected: {
  shellExec: "YOUR MONITOR POWER ON SHELL COMMAND"
},
```
Add that in configuration of this module.

**Comment by eouia** [comment]
Or you can assign specific gesture pattern to turn on monitor.

**Comment by smiley-2** [comment]
great !

thank you!

**Comment by eouia** [comment]
I'll close this. have a nice day.
